services:
  mysql-db:
    image: mysql:8.0
    container_name: j3dental-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: j3dental_db
      MYSQL_USER: j3_user
      MYSQL_PASSWORD: j3_password_123
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend-api:
    image: j3dental-api:latest
    container_name: j3dental-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=j3dental_db;Uid=j3_user;Pwd=j3_password_123;
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
